---
run:
  concurrency: 6
  deadline: 5m
  skip-dirs-use-default: true
  skip-dirs:
    - contrib
    - dependencies
    - test
    - pkg/spec
    - vendor
  skip-files:
    - iopodman.go
    - swagger.go
  modules-download-mode: readonly
linters:
  enable-all: true
  disable:
    # All these break for one reason or another
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - golint
    - lll
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - deadcode
    - depguard
    - errcheck
    - gocritic
    - gosec
    - maligned
linters-settings:
  errcheck:
    check-blank: false
    ignore: encoding/json:^Unmarshal,fmt:.*
